[BUG] Fix Tutorial Notebooks
jdb78/pytorch-forecasting pull request #1599
Opened 2024-08-23 05:07 UTC by XinyuWuu

This PR fixes bugs when running notebook tutorials. 

Added or moved some dependencies to core dependency set.

Fixed some `numpy2` and `optuna-integrations` problems.

Removed `os.chdir("../../..")` in notebooks.

`requests` replaced by `urllib.request.urlretrieve`.

fix https://github.com/jdb78/pytorch-forecasting/issues/1539

2024-08-23 06:03 UTC, fkiraly requested changes
Nice!

Could you kindly split this up into two PR, "notebook" and "other" fixes?

2024-08-24 03:28 UTC, XinyuWuu commented
> Nice!
> 
> Could you kindly split this up into two PR, "notebook" and "other" fixes?

Notebooks are seperated to #1615.

2024-08-24 04:28 UTC, XinyuWuu commented
@fkiraly It seems that new macos runners with Apple silicon don’t have access to MPS hardware. Setting it to `macos-13` solved the problems.

2024-08-25 08:41 UTC, fkiraly commented on pytorch_forecasting/models/base_model.py
> +from numpy import iterable
no request, just making a note: *this is fine* wrt downwards compatibility because this is also an alternative import location for `numpy 1`.

2024-08-25 08:48 UTC, merged