WIP: Feature/beta distribution metric
jdb78/pytorch-forecasting pull request #160
Opened 2020-11-17 21:27 UTC by JakeForsey

Attempt at implementing Beta distribution for data in range [0, 1].

I could use some thoughts on:
 * Changes to GroupNormalizer and TorchNormalizer
 * New Normalizer

NOTE: Test is not yet finished (need a normalizer that makes sense....)

2020-11-21 10:30 UTC, jdb78 commented
Couple of thoughts here:
* It might make sense to reparametrize as by mean and shape beta as α = μν, β = (1 − μ)ν where the original concentrations are parameters α and β.
* Normalization should probably be a deterministic/not-learned transformation to scale data to 0-1. As the beta distribution as bounds, the user should know upfront how to normalize. This is could be done before feeding to the timeseries dataset by the user. Then, you can use the standard target normalizers - no need to modify them.
* Finally, using the target scale (mean, std), in the metric's `rescale_parameters()` method, you could try μ_new= sigmoid(μ + mean) and ν_new = softplus(ν) * μ_new * (1- μ_new) / std**2  (just a quick suggestion, there might be better ways to to calculate μ_new and ν_new). From  μ_new and ν_new, you can calculate α and β to create the distribution from which you can sample.
As always, [the wikipedia article on the Beta distribution](https://en.wikipedia.org/wiki/Beta_distribution) is helpful for reparametrizations.

I hope this is helpful!

2020-11-25 12:39 UTC, JakeForsey commented
I've done the re-parameterisation and my model is training well. 

I'm not sure how to write a proper tests for it, in a bit over my head.

2020-11-26 10:12 UTC, jdb78 requested changes
Looks really good! Thanks a lot for all the hard work! Just minimal formatting changes and a suggestion on the parametrization. How are you training? Maybe you could write some documentation as to how it can be used by a user and what they should take consider.

2020-11-26 10:12 UTC, jdb78 commented on pytorch_forecasting/metrics.py
> +        scaled_mean = torch.sigmoid(parameters[..., 0] + target_scale[..., 0].unsqueeze(1))
I wonder if it works even better if you take `torch.logit(target_scale[..., 0])` instead of `target_scale[..., 0]`.

2020-11-26 10:12 UTC, jdb78 commented on tests/test_metrics.py
> +    BetaDistributionLoss,
Could you run black and isort (best is to use the pre-commit hooks to ensure correct formatting)?

2020-12-02 18:44 UTC, jdb78 commented
Integrated the beta distribution loss - should work now

2020-12-02 19:41 UTC, jdb78 approved these changes

2020-12-03 10:15 UTC, JakeForsey commented
This is awesome, much better than what I was messing around with.

2020-12-03 10:21 UTC, merged